// System includes
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <cstdlib>
#include <iostream>

// ImGui includes
#include "imgui.h"
#include "../third_party/imgui/backends/imgui_impl_glfw.h"
#include "../third_party/imgui/backends/imgui_impl_opengl3.h"

// SEP Engine includes
#include "sep_engine_wrapper.h"
#include "cycles_renderer_adapter.h"

// Demo manager and demos
// Note: demo_manager.hpp indirectly includes pattern.hpp, so we don't need to include it directly
#include "demos/demo_manager.hpp"

// Function to register all demos
namespace sep {
namespace workbench {
    void registerDemos();  // Forward declaration
}
}

// Global variable to track emergency START button clicks
static bool emergencyStartClicked = false;

// Error callback for GLFW
static void error_callback(int error, const char* description)
{
    std::cerr << "GLFW Error " << error << ": " << description << std::endl;
}

// Debug callback for OpenGL errors
void GLAPIENTRY messageCallback(GLenum /*source*/, GLenum type, GLuint /*id*/,
                                GLenum severity, GLsizei /*length*/,
                                const GLchar* message, const void* /*userParam*/)
{
    if (type == GL_DEBUG_TYPE_ERROR) {
        fprintf(stderr, "GL ERROR: type = 0x%x, severity = 0x%x, message = %s\n",
                type, severity, message);
    }
}

int main(int /* argc */, char * /* argv */[])
{
    // Set environment variables for display
    setenv("DISPLAY", ":0", 0);  // Only set if not already set
    
    // Force libdecor to use the xdg-shell backend instead of GTK
    setenv("LIBDECOR_PLUGIN", "xdg-shell", 1);
    
    // Set GLFW error callback
    glfwSetErrorCallback(error_callback);
    
    std::cout << "Initializing GLFW..." << std::endl;
    if (!glfwInit())
    {
        std::cerr << "Failed to initialize GLFW!" << std::endl;
        return -1;
    }
    std::cout << "GLFW initialized successfully." << std::endl;
    
    // Configure GLFW window hints - Use core profile for modern OpenGL
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_VISIBLE, GLFW_TRUE);
    glfwWindowHint(GLFW_FOCUSED, GLFW_TRUE);
    
    // Create window with graphics context
    GLFWwindow* window = glfwCreateWindow(1280, 720, "SEP Workbench", nullptr, nullptr);
    if (!window)
    {
        std::cerr << "Failed to create GLFW window!" << std::endl;
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(window);
    
    // Initialize GLEW - always use experimental flag for modern OpenGL contexts
    std::cout << "Initializing GLEW..." << std::endl;
    
    // Set experimental flag before initialization
    glewExperimental = GL_TRUE;
    GLenum glew_err = glewInit();
    
    if (glew_err != GLEW_OK)
    {
        std::cerr << "GLEW initialization failed: " << glewGetErrorString(glew_err) << std::endl;
        
        // Continue anyway - attempt to get OpenGL information
        std::cout << "Attempting to get OpenGL information..." << std::endl;
    }
    else
    {
        std::cout << "GLEW initialized successfully." << std::endl;
        
        // Clear any error that might have been generated by GLEW initialization
        // This is a known issue with some GLEW versions and OpenGL core profile
        GLenum err = glGetError();
        if (err != GL_NO_ERROR) {
            std::cout << "Clearing OpenGL error after GLEW init: " << err << std::endl;
        }
    }
    
    // Print OpenGL information regardless of GLEW initialization status
    std::cout << "OpenGL Version: " << glGetString(GL_VERSION) << std::endl;
    std::cout << "OpenGL Vendor: " << glGetString(GL_VENDOR) << std::endl;
    std::cout << "OpenGL Renderer: " << glGetString(GL_RENDERER) << std::endl;
    
    // Continue with fallback rendering mode if GLEW failed
    if (glew_err != GLEW_OK)
    {
        std::cout << "Continuing with fallback rendering mode..." << std::endl;
    }
    
    // Enable vsync
    glfwSwapInterval(1);

    // Setup ImGui
    std::cout << "Initializing ImGui..." << std::endl;
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;  // Enable Keyboard Controls
    
    // Setup ImGui style
    ImGui::StyleColorsDark();
    
    // Setup Platform/Renderer backends
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init("#version 120"); // Use GLSL 120 for OpenGL 2.1
    
    std::cout << "ImGui initialized successfully." << std::endl;

    // Create our SEP engine and renderer
    std::cout << "Creating SEP engine and renderer..." << std::endl;
    auto engine = sep::createEngine();
    auto renderer = std::unique_ptr<sep::workbench::Renderer>(new sep::workbench::Renderer());
    renderer->init(1280, 720);
    
    // Create the adapter to make our Renderer work with the CyclesRenderer interface
    auto cycles_adapter = std::unique_ptr<sep::workbench::CyclesRendererAdapter>(
        new sep::workbench::CyclesRendererAdapter(renderer.get()));
    
    // Initialize the demo manager and register all demos
    std::cout << "Initializing demo manager..." << std::endl;
    auto& manager = sep::workbench::DemoManager::getInstance();
    manager.initialize(engine.get(), cycles_adapter.get());
    
    // Set the demo manager in the renderer for START button interaction
    renderer->setDemoManager(&manager);
    
    // Set up mouse button callback for handling clicks on the START button
    glfwSetMouseButtonCallback(window, [](GLFWwindow* window, int button, int action, int /*mods*/) {
        if (button == GLFW_MOUSE_BUTTON_LEFT && action == GLFW_PRESS) {
            // Get cursor position
            double xpos, ypos;
            glfwGetCursorPos(window, &xpos, &ypos);
            
            // Check if click is within the emergency START button area
            // The START button is in the center of the screen (1280/2 ± 200, 720/2 ± 200)
            bool isInEmergencyStartButton =
                xpos >= 1280/2 - 200 && xpos <= 1280/2 + 200 &&
                ypos >= 720/2 - 200 && ypos <= 720/2 + 200;
                
            if (isInEmergencyStartButton) {
                // Use the global variable
                emergencyStartClicked = true;
                std::cout << "EMERGENCY START BUTTON CLICKED!" << std::endl;
            }
            
            // Also try the renderer's click handler as a backup
            auto renderer = static_cast<sep::workbench::Renderer*>(glfwGetWindowUserPointer(window));
            if (renderer) {
                renderer->handleMouseClick(xpos, ypos);
            }
        }
    });
    
    // Store renderer pointer for callbacks
    glfwSetWindowUserPointer(window, renderer.get());
    
    // Register all demos using the function from register_demos.cpp
    sep::workbench::registerDemos();
    
    // Switch to the genesis demo by default
    if (!manager.switchToDemo("genesis")) {
        std::cerr << "Failed to switch to genesis demo!" << std::endl;
    } else {
        std::cout << "Switched to genesis demo successfully." << std::endl;
    }

    // Main loop
    std::cout << "Entering main loop..." << std::endl;
    while (!glfwWindowShouldClose(window))
    {
        // Poll and handle events
        glfwPollEvents();

        // Start the ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        // Clear the screen with a bright color to make it obvious if rendering is working
        glClearColor(0.2f, 0.1f, 0.3f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        
        // Draw a simple colored rectangle directly in the main loop
        // This should be visible even if the renderer fails
        static int frame_count = 0;
        frame_count++;
        
        // Set up orthographic projection for 2D rendering
        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        glOrtho(0.0, 1280, 0.0, 720, -1.0, 1.0);
        
        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
        
        // EMERGENCY RENDERING: Draw a very bright red rectangle in the center of the screen
        glColor4f(1.0f, 0.0f, 0.0f, 1.0f); // Pure red
        glBegin(GL_QUADS);
        glVertex2f(1280/2 - 200, 720/2 - 200);
        glVertex2f(1280/2 + 200, 720/2 - 200);
        glVertex2f(1280/2 + 200, 720/2 + 200);
        glVertex2f(1280/2 - 200, 720/2 + 200);
        glEnd();
        
        // Draw a white border
        glColor4f(1.0f, 1.0f, 1.0f, 1.0f); // Pure white
        glLineWidth(5.0f); // Thicker line
        glBegin(GL_LINE_LOOP);
        glVertex2f(1280/2 - 200, 720/2 - 200);
        glVertex2f(1280/2 + 200, 720/2 - 200);
        glVertex2f(1280/2 + 200, 720/2 + 200);
        glVertex2f(1280/2 - 200, 720/2 + 200);
        glEnd();
        
        // Draw "START" text using simple line segments - LARGE and BRIGHT GREEN
        glColor4f(0.0f, 1.0f, 0.0f, 1.0f); // Bright green
        glLineWidth(10.0f); // Very thick lines for visibility
        
        // Draw "S" - larger and centered
        int textY = 720/2 - 50; // Position in the middle of the red square
        int textX = 1280/2 - 120; // Start position for the text
        int charWidth = 60; // Width of each character
        int charHeight = 100; // Height of each character
        
        // S
        glBegin(GL_LINE_STRIP);
        glVertex2f(textX, textY);
        glVertex2f(textX + charWidth, textY);
        glVertex2f(textX + charWidth, textY + charHeight/2);
        glVertex2f(textX, textY + charHeight/2);
        glVertex2f(textX, textY + charHeight);
        glVertex2f(textX + charWidth, textY + charHeight);
        glEnd();
        textX += charWidth + 20;
        
        // T
        glBegin(GL_LINES);
        glVertex2f(textX + charWidth/2, textY);
        glVertex2f(textX + charWidth/2, textY + charHeight);
        glVertex2f(textX, textY);
        glVertex2f(textX + charWidth, textY);
        glEnd();
        textX += charWidth + 20;
        
        // A
        glBegin(GL_LINE_STRIP);
        glVertex2f(textX, textY + charHeight);
        glVertex2f(textX + charWidth/2, textY);
        glVertex2f(textX + charWidth, textY + charHeight);
        glEnd();
        glBegin(GL_LINES);
        glVertex2f(textX + charWidth/4, textY + charHeight/2);
        glVertex2f(textX + 3*charWidth/4, textY + charHeight/2);
        glEnd();
        textX += charWidth + 20;
        
        // R
        glBegin(GL_LINE_STRIP);
        glVertex2f(textX, textY);
        glVertex2f(textX, textY + charHeight);
        glVertex2f(textX + charWidth, textY + charHeight);
        glVertex2f(textX + charWidth, textY + charHeight/2);
        glVertex2f(textX, textY + charHeight/2);
        glEnd();
        glBegin(GL_LINES);
        glVertex2f(textX, textY + charHeight/2);
        glVertex2f(textX + charWidth, textY);
        glEnd();
        textX += charWidth + 20;
        
        // T
        glBegin(GL_LINES);
        glVertex2f(textX + charWidth/2, textY);
        glVertex2f(textX + charWidth/2, textY + charHeight);
        glVertex2f(textX, textY);
        glVertex2f(textX + charWidth, textY);
        glEnd();
        
        // Add instructions text below
        glColor4f(1.0f, 1.0f, 1.0f, 1.0f); // White
        glLineWidth(3.0f); // Thinner lines for instructions
        
        // Draw "CLICK HERE" text below the START button
        textY = 720/2 - 180;
        textX = 1280/2 - 100;
        
        // Draw an arrow pointing up
        glBegin(GL_LINES);
        glVertex2f(1280/2, textY + 30);
        glVertex2f(1280/2, textY + 80);
        glEnd();
        glBegin(GL_TRIANGLES);
        glVertex2f(1280/2, textY + 90);
        glVertex2f(1280/2 - 15, textY + 70);
        glVertex2f(1280/2 + 15, textY + 70);
        glEnd();
        
        // Print debug info
        std::cout << "Rendering in fallback mode (frame: " << frame_count << ")" << std::endl;
        
        // Create a large START button in the center of the screen
        // This will be visible even if other UI elements aren't rendering correctly
        ImGui::SetNextWindowPos(ImVec2(1280/2 - 150, 720/2 - 100), ImGuiCond_Always);
        ImGui::SetNextWindowSize(ImVec2(300, 200), ImGuiCond_Always);
        ImGui::Begin("START MENU", nullptr,
            ImGuiWindowFlags_NoTitleBar |
            ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoMove |
            ImGuiWindowFlags_NoScrollbar |
            ImGuiWindowFlags_NoCollapse);
        
        // Add a title and description
        ImGui::TextColored(ImVec4(1.0f, 1.0f, 0.0f, 1.0f), "SEP WORKBENCH");
        ImGui::Separator();
        ImGui::TextWrapped("Click START to initialize the demo suite");
        ImGui::Spacing();
        ImGui::Spacing();
        
        // Add a large START button
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.2f, 0.8f, 0.2f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0.3f, 0.9f, 0.3f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0.1f, 0.7f, 0.1f, 1.0f));
        
        // Center the button
        float buttonWidth = 200.0f;
        float buttonHeight = 80.0f;
        ImGui::SetCursorPosX((ImGui::GetWindowWidth() - buttonWidth) * 0.5f);
        
        if (ImGui::Button("START", ImVec2(buttonWidth, buttonHeight))) {
            // Switch to the genesis demo when START is clicked
            manager.switchToDemo("genesis");
        }
        ImGui::PopStyleColor(3);
        
        ImGui::End();
        
        // Create a demo selection window with a larger size and more visible elements
        ImGui::SetNextWindowPos(ImVec2(50, 50), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowSize(ImVec2(400, 300), ImGuiCond_FirstUseEver);
        ImGui::Begin("SEP Demos", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
        
        // Add a title and description
        ImGui::TextColored(ImVec4(1.0f, 1.0f, 0.0f, 1.0f), "SEP Workbench Demo Selection");
        ImGui::Separator();
        ImGui::TextWrapped("Select a demo to visualize different aspects of the SEP Engine.");
        ImGui::Spacing();
        
        // Make buttons larger and more colorful
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.2f, 0.4f, 0.8f, 0.8f));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0.3f, 0.5f, 0.9f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0.1f, 0.3f, 0.7f, 1.0f));
        
        if (ImGui::Button("Genesis Pattern", ImVec2(180, 30))) manager.switchToDemo("genesis");
        ImGui::SameLine(); ImGui::Text("- Basic pattern visualization");
        
        if (ImGui::Button("Neural Network", ImVec2(180, 30))) manager.switchToDemo("neural");
        ImGui::SameLine(); ImGui::Text("- Neural network simulation");
        
        if (ImGui::Button("Memory Garden", ImVec2(180, 30))) manager.switchToDemo("memory");
        ImGui::SameLine(); ImGui::Text("- Memory hierarchy visualization");
        
        if (ImGui::Button("Flocking Simulation", ImVec2(180, 30))) manager.switchToDemo("flocking");
        ImGui::SameLine(); ImGui::Text("- Emergent behavior demo");
        
        if (ImGui::Button("Cosmological Simulation", ImVec2(180, 30))) manager.switchToDemo("cosmo");
        ImGui::SameLine(); ImGui::Text("- Space-time patterns");
        
        if (ImGui::Button("Digital Physics", ImVec2(180, 30))) manager.switchToDemo("physics");
        ImGui::SameLine(); ImGui::Text("- Physical simulation");
        
        if (ImGui::Button("Drug Discovery", ImVec2(180, 30))) manager.switchToDemo("drug");
        ImGui::SameLine(); ImGui::Text("- Molecular pattern matching");
        
        if (ImGui::Button("Audio Visualizer", ImVec2(180, 30))) manager.switchToDemo("audio");
        ImGui::SameLine(); ImGui::Text("- Audio pattern analysis");
        
        ImGui::PopStyleColor(3);
        
        // Add status information
        ImGui::Separator();
        ImGui::Text("Current Demo: %s", manager.getCurrentDemo().c_str());
        ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / io.Framerate, io.Framerate);
        
        ImGui::End();
        
        // Add a second window with debug information
        ImGui::SetNextWindowPos(ImVec2(500, 50), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowSize(ImVec2(300, 200), ImGuiCond_FirstUseEver);
        ImGui::Begin("Debug Info", nullptr);
        ImGui::Text("OpenGL Version: %s", glGetString(GL_VERSION));
        ImGui::Text("OpenGL Vendor: %s", glGetString(GL_VENDOR));
        ImGui::Text("OpenGL Renderer: %s", glGetString(GL_RENDERER));
        ImGui::Text("ImGui Version: %s", IMGUI_VERSION);
        ImGui::End();

        // Normal rendering pipeline is now enabled
        // The emergency direct rendering code has been removed
        
        // Check for OpenGL errors
        GLenum err = glGetError();
        if (err != GL_NO_ERROR) {
            std::cerr << "OpenGL error during emergency rendering: " << err << std::endl;
        }
        
        // Check if the START button was clicked via our fallback UI
        if (renderer->wasStartButtonClicked()) {
            std::cout << "START button clicked via fallback UI, switching to genesis demo" << std::endl;
            manager.switchToDemo("genesis");
            renderer->resetStartButtonClicked();
        }
        
        // Check if the emergency START button was clicked
        if (emergencyStartClicked) {
            std::cout << "EMERGENCY START BUTTON CLICKED! Switching to genesis demo" << std::endl;
            manager.switchToDemo("genesis");
            emergencyStartClicked = false; // Reset the flag
        }
        
        // Use normal rendering pipeline
        manager.on_update(0.016f); // ~60 FPS
        manager.on_render();
        
        // Try to render ImGui anyway
        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
        
        // Swap buffers
        glfwSwapBuffers(window);
        
        // Print debug info every 10 frames
        static int emergency_frame_count = 0;
        emergency_frame_count++;
        if (emergency_frame_count % 10 == 0) {
            std::cout << "Emergency rendering mode (frame: " << emergency_frame_count << ")" << std::endl;
        }
    }

    // Cleanup
    std::cout << "Cleaning up..." << std::endl;
    
    // Clean up renderer resources first
    if (renderer) {
        renderer->cleanup();
    }
    
    // Clean up other resources
    manager.on_unload();
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
    glfwDestroyWindow(window);
    glfwTerminate();
    
    std::cout << "Exiting successfully." << std::endl;
    return 0;
}