#include <GL/glew.h>
#include <GLFW/glfw3.h>

#include <iostream>

#include "core/logging.h"             // For our logger
#include "cycles_renderer_adapter.h"  // Cycles renderer
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include "sep_engine_wrapper.h"              // SEP Engine wrapper
#include "workbench/demos/demo_manager.hpp"  // Demo manager

// Forward declaration for demo registration function
namespace sep
{
    namespace workbench
    {
        void registerDemos();
    }
}  // namespace sep

// Key callback function for GLFW
void key_callback(GLFWwindow* /*window*/, int key, int /*scancode*/, int action, int /*mods*/)
{
    if (action == GLFW_PRESS)
    {
        auto& demoManager = sep::workbench::DemoManager::getInstance();

        // Handle demo selection keys (1-9)
        if (key >= GLFW_KEY_1 && key <= GLFW_KEY_9)
        {
            const std::map<int, std::string> keyToDemoMap = {
                {GLFW_KEY_1, "genesis"},  {GLFW_KEY_2, "neural"}, {GLFW_KEY_3, "memory"},
                {GLFW_KEY_4, "flocking"}, {GLFW_KEY_5, "cosmo"},  {GLFW_KEY_6, "cosmo_sim"},
                {GLFW_KEY_7, "physics"},  {GLFW_KEY_8, "drug"},   {GLFW_KEY_9, "audio"}};

            auto it = keyToDemoMap.find(key);
            if (it != keyToDemoMap.end())
            {
                demoManager.switchToDemo(it->second);
            }
        }
        else
        {
            // Pass other keys to the current demo
            demoManager.on_key(key);
        }
    }
}

int main()
{
    // 1. Initialize GLFW and Create a Window
    if (!glfwInit())
    {
        std::cerr << "Failed to initialize GLFW" << std::endl;
        return -1;
    }

    // First try with compatibility profile
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_COMPAT_PROFILE);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);

    GLFWwindow* window = glfwCreateWindow(1280, 720, "SEP Workbench", nullptr, nullptr);

    // If that fails, try with no specific profile (more compatible)
    if (!window)
    {
        std::cout << "Failed to create window with compatibility profile, trying fallback..."
                  << std::endl;
        glfwDefaultWindowHints();
        glfwWindowHint(GLFW_VISIBLE, GLFW_TRUE);
        window = glfwCreateWindow(1280, 720, "SEP Workbench (Fallback)", nullptr, nullptr);

        // If that still fails, try with even more basic settings
        if (!window)
        {
            std::cout << "Failed with default hints, trying minimal configuration..." << std::endl;
            glfwDefaultWindowHints();
            glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
            glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
            window = glfwCreateWindow(1280, 720, "SEP Workbench (Legacy)", nullptr, nullptr);

            if (!window)
            {
                std::cerr << "Failed to create GLFW window with all configurations" << std::endl;
                glfwTerminate();
                return -1;
            }
        }
    }
    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);  // Enable vsync

    // Set key callback
    glfwSetKeyCallback(window, key_callback);

    // 2. Initialize GLEW
    glewExperimental = GL_TRUE;
    GLenum err = glewInit();
    if (err != GLEW_OK)
    {
        std::cerr << "GLEW initialization failed: " << glewGetErrorString(err) << std::endl;
        glfwTerminate();
        return -1;
    }

    // Clear any error that might have been generated by glewInit
    glGetError();

    // 3. Initialize SEP Core Logger
    sep::logging::Manager::initialize();
    sep::logging::LoggerConfig log_config;
    log_config.name = "workbench";
    auto logger = sep::logging::Manager::getInstance().createLogger("workbench", log_config);
    logger->info("Workbench shell initialized.");

    // 4. Initialize SEP Engine and Renderer
    std::unique_ptr<sep::Engine> engine = sep::createEngine();
    std::unique_ptr<sep::CyclesRenderer> renderer = sep::createRenderer();

    engine->initialize();
    renderer->initialize();

    // 5. Initialize the demo manager
    auto& demoManager = sep::workbench::DemoManager::getInstance();
    demoManager.initialize(engine.get(), renderer.get());

    // 6. Register available demos
    sep::workbench::registerDemos();
    logger->info("Demos registered and ready.");

    // 7. Initialize ImGui
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGui::StyleColorsDark();
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init();

    // 8. Start with the default demo
    demoManager.switchToDemo("genesis");

    // 9. Main Loop
    float lastFrameTime = static_cast<float>(glfwGetTime());

    while (!glfwWindowShouldClose(window))
    {
        // Calculate delta time
        float currentTime = static_cast<float>(glfwGetTime());
        float deltaTime = currentTime - lastFrameTime;
        lastFrameTime = currentTime;

        // Poll events
        glfwPollEvents();

        // Start the ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        // Update the current demo
        demoManager.on_update(deltaTime);

        // Render the current demo
        demoManager.on_render();

        // Let the current demo render its UI
        if (demoManager.getCurrentDemo() != "")
        {
            demoManager.on_ui_render();
        }

        // Render the main UI
        ImGui::Begin("SEP Workbench");
        ImGui::Text("Application average %.3f ms/frame (%.1f FPS)",
                    1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);

        // Display current demo
        ImGui::Text("Current Demo: %s", demoManager.getCurrentDemo().c_str());

        // Display available demos
        ImGui::Separator();
        ImGui::Text("Available Demos (Press key to select):");
        ImGui::Columns(2, "demos");
        ImGui::Text("Key");
        ImGui::NextColumn();
        ImGui::Text("Demo");
        ImGui::NextColumn();
        ImGui::Separator();

        // List all demos with their keyboard shortcuts
        ImGui::Text("1");
        ImGui::NextColumn();
        ImGui::Text("Genesis Pattern Demo");
        ImGui::NextColumn();

        ImGui::Text("2");
        ImGui::NextColumn();
        ImGui::Text("Neural Demo");
        ImGui::NextColumn();

        ImGui::Text("3");
        ImGui::NextColumn();
        ImGui::Text("Memory Garden Demo");
        ImGui::NextColumn();

        ImGui::Text("4");
        ImGui::NextColumn();
        ImGui::Text("Flocking Demo");
        ImGui::NextColumn();

        ImGui::Text("5");
        ImGui::NextColumn();
        ImGui::Text("Cosmo Demo");
        ImGui::NextColumn();

        ImGui::Text("6");
        ImGui::NextColumn();
        ImGui::Text("Cosmo Sim Demo");
        ImGui::NextColumn();

        ImGui::Text("7");
        ImGui::NextColumn();
        ImGui::Text("Digital Physics Demo");
        ImGui::NextColumn();

        ImGui::Text("8");
        ImGui::NextColumn();
        ImGui::Text("Drug Discovery Demo");
        ImGui::NextColumn();

        ImGui::Text("9");
        ImGui::NextColumn();
        ImGui::Text("Audio Visualizer Demo");
        ImGui::NextColumn();

        ImGui::Columns(1);
        ImGui::End();

        // Render ImGui
        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        // Swap buffers
        glfwSwapBuffers(window);
    }

    // 10. Cleanup
    logger->info("Shutting down workbench shell.");

    // Unload the current demo
    demoManager.on_unload();

    // Cleanup engine and renderer
    engine->shutdown();

    // Cleanup ImGui and GLFW
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
    glfwDestroyWindow(window);
    glfwTerminate();

    return 0;
}
